BookFace/BookFace/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth.views import LogoutView
from django.urls import include, path, re_path

from myblog import views

urlpatterns = [
    re_path(r'', 
        include('myblog.urls',
        namespace='myblog')),
    path('admin/', 
        admin.site.urls),
    path(
        'logout/',
        LogoutView.as_view(next_page='/accounts/login/'),
        name='logout',
    ),
    path('api/',
    include('api.urls')),
]

BookFace/api/urls.py
from django.urls import path

from . import views 

urlpatterns = [
    path('postlist/',
views.PostList.as_view()),
    path('commentlist/',
views.CommentList.as_view()),
    path('signup/',
views.signup),
    path('login/',
views.login),
    path('postlist/<int:pk>',
views.PostRetrieveUpdateDestroy.as_view()),
    path('commentlist/<int:pk>',
views.CommentRetrieveUpdateDestroy.as_view()),
]

BookFace/myblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path

from myblog import views

app_name = 'myblog'
urlpatterns = [
    re_path(
        r'about/$', 
        views.AboutView.as_view(), 
        name='about'),
    re_path(
        r'$', 
        views.AllPost.as_view(), 
        name='post_list'),
    re_path(
        r'post/(?P<pk>\d+)/$', 
        views.PostDetail.as_view(), 
        name='post_detail'
    ),
    re_path(
        r'post/new/$', 
        views.CreatePostView.as_view(), 
        name='post_new'),
    re_path(
        r'post/(?P<pk>\d+)/edit/$',
        views.PostUpdateView.as_view(),
        name='post_edit',
    ),
    re_path(
        r'post/(?P<pk>\d+)/remove/$',
        views.DeletePostView.as_view(),
        name='post_remove',
    ),
    re_path(
        r'drafts/$', 
        views.PostDraftList.as_view(), 
        name='post_draft_list'
    ),
    re_path(
        r'post/(?P<pk>\d+)/comment/$',
        views.CreateCommentView.as_view(),
        name='add_comment_to_post',
    ),
    # re_path(r'comment/(?P<pk>\d+)/approve/$', views.comment_approve , name='comment_approve'),
    # re_path(r'comment/(?P<pk>\d+)/remove/$', views.comment_remove , name='comment_remove'),
    re_path(
        r'post/(?P<pk>\d+)/publish/$', 
        views.post_publish, 
        name='post_publish'
    ),
    re_path(
            r'wall/$', 
            views.Wall.as_view(), 
            name='wall'),
    re_path(
            r'accounts/login/$', 
            views.user_login, 
            name='user_login'),
    re_path(
        r'accounts/registration/$', 
        views.registration, 
        name='registration'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookFace/myblog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    username = models.CharField(max_length=200, default='')
    email = models.EmailField(max_length=254, default='')
    # profile_picture = models.ImageField(upload_to='media/account_picture', blank=True)
    password = models.CharField(max_length=200, default='')
    confirm_password = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.user.username


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    picture = models.ImageField(
        upload_to='media/profile_pics/', blank=True, null=True
    )
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("myblog:post_detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        'myblog.Post', related_name='comment', on_delete=models.CASCADE
    )
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

BookFace/myblog/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm

from myblog.models import Comment, Post, UserProfileInfo


class UserForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = UserProfileInfo
        fields = ('username', 'email', 'confirm_password')



class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('title', 'text', 'picture')
        widgets = {
            
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'}),
        }

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('text',)

    widgets = {
        'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'}),
    }

BookFace/myblog/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import (
    LoginRequiredMixin, 
    UserPassesTestMixin
)
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.db.utils import IntegrityError
from django.http import (
    HttpResponse,
    HttpResponseRedirect
)
from django.shortcuts import (
    get_object_or_404, 
    redirect, 
    render
)
from django.urls import (
    reverse, 
    reverse_lazy
)
from django.utils import timezone
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)

from myblog.forms import (
    CommentForm,
    PostForm, 
    UserForm
)
from myblog.models import (
    Comment, 
    Post, 
    User, 
    UserProfileInfo
)


class AboutView(TemplateView):
    template_name = 'about.html'


class PostDraftList(ListView):
    model = Post
    paginate_by = 5
    context_object_name = 'post'
    template_name = 'myblog/post_draft_list.html'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            posts = Post.objects.filter(
                author=self.request.user, published_date__isnull=True
            ).order_by('create_date')
            return posts
        else:
            posts = Post.objects.none()
            return posts


class AllPost(ListView):
    model = Post
    paginate_by = 5
    context_object_name = 'post'
    template_name = 'myblog/post_list.html'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            posts = Post.objects.filter(author=self.request.user)
        else:
            posts = Post.objects.none()
        return posts


class Wall(ListView):
    model = Post
    template_name = 'myblog/wall.html'
    context_object_name = 'post'
    paginate_by = 5

    def get_queryset(self):
        post = Post.objects.all()
        if not self.request.user.is_authenticated:
            return redirect('accounts/login')
        return post


class PostDetail(DetailView):
    model = Post
    template_name = 'myblog/post_detail.html'
    context_object_name = 'post'


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'myblog/post_detail'
    form_class = PostForm
    model = Post

    def form_valid(self, form):
        form.instance.author = self.request.user
        picture = form.cleaned_data['picture']
        if picture:
            form.instance.picture = picture
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'myblog/post_detail.html'
    model = Post
    form_class = PostForm


class DeletePostView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('myblog:post_list')

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('myblog:post_detail', pk=pk)


@method_decorator(login_required, name='dispatch')
class CreateCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'myblog/comment_form.html'

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        comment = form.save(commit=False)
        comment.post = post
        comment.author = self.request.user
        comment.save()
        previous_page_url = self.request.session.get('previous_page_url', '/')
        return redirect(previous_page_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['previous_page_url'] = self.request.META.get('HTTP_REFERER', '/')
        return context


def registration(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST, files=request.FILES)
        if user_form.is_valid():
            username = user_form.cleaned_data.get('username')
            email = user_form.cleaned_data.get('email')
            password = user_form.cleaned_data.get('password')
            confirm_password = user_form.cleaned_data.get('confirm_password')
            email_exists = User.objects.filter(email=email).exists()
            if password != confirm_password:
                user_form.add_error('username', f'Check your password please!')
            elif email_exists:
                user_form.add_error(
                    'email', f'This email is already registered.'
                )
            else:
                try:
                    user = User.objects.create_user(
                        username=username, email=email, password=password
                    )
                    user.set_password(
                        password
                    )  # Hash the password for UserProfileInfo
                    user.save()
                    registered = True
                except IntegrityError as e:
                    user_form.add_error(
                        'username',
                        f'Username {username} already exists. Please choose another username.',
                    )
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(
        request,
        'myblog/registration.html',
        {'user_form': user_form, 'registered': registered},
    )


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('myblog:post_list'))

            else:
                return HttpResponse("ACCOUNT IS NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password: {}".format(username, password))
            return render(request, 'myblog/user_login.html', {})
    else:
        return render(request, 'myblog/user_login.html', {})

BookFace/myblog/templates/myblog/about.html
{% extends "myblog/base.html" %}
{% block content %}
<h1>About this project</h1>
{% endblock %}

BookFace/myblog/templates/myblog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BLOG</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/myblog.css' %}">
</head>
<body>
    <nav class="navbar navbar-default custom-navbar">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand bigbrand" href="{% url 'myblog:post_list' %}">My blog</a></li>
                <li><a href="{% url 'myblog:about' %}">About</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a  href="{% url 'myblog:post_new' %}">New Post</a></li>
                <li><a  href="{% url 'myblog:post_draft_list' %}">Drafts</a></li>
                <li><a  href="{% url 'logout' %}">Logout</a></li>
                <li><a href="{% url 'myblog:wall' %}">Wall</a></li>
                <li><a>WELCOME {{user.username}}</a></li>
                <!-- <img class="myblog_page" src="{{ .picture.url }}" alt=""/> -->
                {% else %}
                <li><a class="nav navbar-right" href="{% url 'myblog:user_login' %}">Login</a></li>
                <li><a class="nav navbar-right" href="{% url 'myblog:registration' %}">Registration</a></li>
                {% endif %}

            </ul>
         
        </div>

    </nav>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                <div class="blog_posts "> 
                    {% block content %}
                    {% endblock  %}
                    
                </div>
                 
            </div>

        </div>
    </div>
    <nav class="list-pages">
        <ul>
            {% for p in paginator.page_range %}
            <li class="page-num">
                <a href="?page={{ p }}">{{ p }}</a>
            </li>
            {% endfor %}
        </ul>
    </nav>
</body>
</html>

BookFace/myblog/templates/myblog/comment_form.html
{% extends "myblog/base.html" %}
{% block content %}
<h1>New comment</h1>
<form class="post-form" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Post comment</button>
</form>
<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

BookFace/myblog/templates/myblog/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Post</h1>
  <p>Are you sure you want to delete "{{ object.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm</button>
    <a href="{% url 'myblog:post_detail' object.pk %}" class="btn btn-default">Cancel</a>
  </form>
{% endblock %}

BookFace/myblog/templates/myblog/post_detail.html
{% extends "myblog/base.html" %}
{% block content %}

<h1 class="posttitle"> {{ post.title }}</h1>
{% if post.picture %}
    <div>
        <img class="myblog_page" src="{{ post.picture.url }}" alt="{{ post.title }}"/>
    </div>
{% endif %}
{% if post.published_date %}
    <div class="dare postdate">
        {{ post.published_date }}
    </div>
{% else %}
    <a class="btn btn-primary" href="{% url 'myblog:post_publish' pk=post.pk %}">Publish</a>
{% endif %}

<p class="postcontent">{{ post.text|upper|linebreaksbr}}</p>

{% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'myblog:post_edit' pk=post.pk %}">
        <span class="glyphicon glyphicon-pencil">Edit</span>
    </a>
    <a class="btn btn-primary" href="{% url 'myblog:post_remove' pk=post.pk %}">
        <span class="glyphicon glyphicon-remove">Remove</span>
    </a>
{% endif %}

<hr>
<a class="btn btn-primary btn-comments" href="{% url 'myblog:add_comment_to_post' pk=post.pk  %}">Add comment</a>

<div class="container">
    {% for comment in post.comment.all %}
         <br>
            {% if user.is_authenticated %}
                {{ comment.create_date }}
                <p>{{ comment.text|upper|linebreaksbr }}</p>
                <p>Posted by:{{comment.author}} </p>
            {% endif %}
            {% empty %}
            <p>No comments</p>
    {% endfor %}
</div>


{% endblock %}

BookFace/myblog/templates/myblog/post_draft_list.html
{% extends "myblog/base.html" %}
{% block content %}
    <!-- {% for post in posts %}
         <div class="post" >
            <p class="created" >Created: {{ post.created_date|date:"D M Y" }}</p>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>

         </div>
    {% endfor %} -->
    {% for post in post %}
        <div class="post">
            <h1><a href="{% url 'myblog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            {% if post.picture %}
                <div>
                    <img class="myblog_page" src="{{ post.picture.url }}" alt="{{ post.title }}"/>
                </div>
            {% endif %}
            <div class="date">
                <p> Published on: {{ post.published_date|date:"D M Y" }}</p>
            </div>
            <!-- <p>Comments:</p>
            <ul>
            {% for comment in post.comment.all %}
                {% if comment.approved_comment %}
                   <li>{{ comment.author }} - {{ comment.text }}</li>
                {% endif %}
            {% endfor %} -->
            </ul>
        </div>
    {% endfor %}
{% endblock %}

BookFace/myblog/templates/myblog/post_form.html
{% extends "myblog/base.html" %}
{% block content %}
    <div class="post-form">
        <h1>New Post</h1>
    
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default" >Save</button>
        </form>
    </div>

    <script>var editor = new MediumeEditor('.editable');</script>
{% endblock %}

BookFace/myblog/templates/myblog/post_list.html
{% extends "myblog/base.html" %}
{% block content %}
<div class="centerstage">
    {% if user.is_authenticated %}
        {% for post in post  %}
                <div class="post">
                    <h1><a href="{% url 'myblog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                    {% if post.picture %}
                        <div>
                            <img class="myblog_page" src="{{ post.picture.url }}" alt="{{ post.title }}"/>
                        </div>
                    {% endif %}
                    <div class="date">
                        <p> Published on: {{ post.published_date|date:"D M Y" }}</p>
                    </div>
                    <p>Comments:</p>
                    <ul>
                    
                    {% for comment in post.comment.all %}
                    
                        <li>{{ comment.author }} - {{ comment.text }}</li>
                    
                    {% endfor %}
                    <a class="btn btn-primary btn-comments" href="{% url 'myblog:add_comment_to_post' pk=post.pk  %}">Add comment</a>

                </ul>
                </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

BookFace/myblog/templates/myblog/registration.html
{% extends 'myblog/base.html' %}
{% load static %}

{% block content %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registration!</h1>
    {% else %}
        <h1>Register here!</h1>
        <h3>Fill out the form:</h3>

        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}

BookFace/myblog/templates/myblog/user_login.html
{% extends 'myblog/base.html' %}
{% load static %}

{% block content %}

<div class="jumbotron">
   <h1>Please Log In</h1>
   <form action="{% url 'myblog:user_login' %}" method="post">
       {% csrf_token %}
       <label for="username">Username:</label>
       <input type="text" name="username" placeholder="Enter Username">
   
       <label for="password">Password:</label>
       <input type="password" name="password">
   
       <input type="submit" value="Login">
   </form>


   
</div>

{% endblock %}

BookFace/myblog/templates/myblog/wall.html
{% extends 'myblog/base.html' %}
{% block content %}

<div class="centerstage">
    {% if user.is_authenticated %}
        {% for post in post %}
                <div class="post">
                    <h1>{{ post.title }}</h1>
                    {% if post.picture %}
                        <div>
                            <img class="myblog_page" src="{{ post.picture.url }}" alt="{{ post.title }}"/>
                        </div>
                    {% endif %}
                    <div class="date">
                        <p> Published on: {{ post.published_date|date:"D M Y" }}</p>
                    </div>
                    <p>Author: {{post.author}}</p>
                    <b><p>{{post.text}}</p></b>
                    
                    <p>Comments:</p>
                    {% for comment in post.comment.all %}
                    
                        <li>{{ comment.author }} - {{ comment.text }}</li>
                   
                    {% endfor %}
                    <hr>
                    <a class="btn btn-primary btn-comments" href="{% url 'myblog:add_comment_to_post' pk=post.pk  %}">Add comment</a>
                    <ul>

                    
                    
                  
                    
                </ul>
                </div>
        {% endfor %}
    {% endif %}
</div>

{% endblock %}